title: Learning Generative Models of 3D Structures
email: daniel_ritchie@brown.edu
description: Website for the tutorial on learning generative models of 3D structures at Eurographics 2019
  ---
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']
